[project]
name = "job-agent"
version = "0.1.0"
description = "Agent that helps with job matching"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "pdfplumber>=0.11.6",
    "semantic-kernel>=1.30.0",
]
